### ISSUE TITLE
Help on setting up environment

### ISSUE THREAD

**Issue by LaCandela** [NVlabs/FB-BEV#17]
I have installed a Conda environment with the dependencies as written on the install page. However, when I try to run a test I get these errors:

(openmmlab) root@xyz:/FB-BEV# python tools/test.py --config log/weights/fbocc-r50-cbgs_depth_16f_16x4_20e.py --checkpoint log/weights/fbocc-r50-cbgs_depth_16f_16x4_20e.pth --out test/test.pkl
Traceback (most recent call last):
  File "tools/test.py", line 303, in <module>
    main()
  File "tools/test.py", line 155, in main
    cfg = Config.fromfile(args.config)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp2fp83puh/tmpcfk_b6pr.py", line 1, in <module>
NameError: name 'false' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f251c1f88b0>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp2fp83puh/tmpcfk_b6pr.py'

Do you have any idea what the solution could be?
This is my pip list:

Package                   Version      Editable project location
------------------------- ------------ -------------------------
absl-py                   1.4.0
addict                    2.4.0
anyio                     4.0.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.2.3
asttokens                 2.4.0
async-lru                 2.0.4
attrs                     23.1.0
Babel                     2.12.1
backcall                  0.2.0
beautifulsoup4            4.12.2
black                     23.9.1
bleach                    6.0.0
cachetools                5.3.1
ccimport                  0.4.2
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
click                     8.1.7
cmake                     3.27.4.1
comm                      0.1.4
contourpy                 1.1.0
cumm-cu114                0.4.11
cycler                    0.11.0
debugpy                   1.7.0
decorator                 5.1.1
defusedxml                0.7.1
descartes                 1.1.0
exceptiongroup            1.1.3
executing                 1.2.0
fastjsonschema            2.18.0
filelock                  3.12.3
fire                      0.5.0
flake8                    6.1.0
fonttools                 4.42.1
fqdn                      1.5.1
google-auth               2.23.0
google-auth-oauthlib      1.0.0
grpcio                    1.58.0
idna                      3.4
imageio                   2.31.3
importlib-metadata        6.8.0
importlib-resources       6.0.1
iniconfig                 2.0.0
ipykernel                 6.25.2
ipython                   8.12.2
ipython-genutils          0.2.0
ipywidgets                8.1.0
isoduration               20.11.0
jedi                      0.19.0
Jinja2                    3.1.2
joblib                    1.3.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
jupyter                   1.0.0
jupyter_client            8.3.1
jupyter-console           6.6.3
jupyter_core              5.3.1
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab                4.0.5
jupyterlab-pygments       0.2.2
jupyterlab_server         2.24.0
jupyterlab-widgets        3.0.8
kiwisolver                1.4.5
lark                      1.1.7
lit                       16.0.6
llvmlite                  0.36.0
lyft-dataset-sdk          0.0.8
Markdown                  3.4.4
MarkupSafe                2.1.3
matplotlib                3.5.2
matplotlib-inline         0.1.6
mccabe                    0.7.0
mistune                   3.0.1
mmcls                     0.25.0
mmcv-full                 1.5.2
mmdet                     2.24.0
mmdet3d                   1.0.0rc4     /FB-BEV
mmsegmentation            0.24.0
mpmath                    1.3.0
mypy-extensions           1.0.0
nbclient                  0.8.0
nbconvert                 7.8.0
nbformat                  5.9.2
nest-asyncio              1.5.7
networkx                  2.2
ninja                     1.11.1
notebook                  7.0.3
notebook_shim             0.2.3
numba                     0.53.0
numpy                     1.20.3
nuscenes-devkit           1.1.10
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
oauthlib                  3.2.2
opencv-python             4.8.0.76
overrides                 7.4.0
packaging                 23.1
pandas                    2.0.3
pandocfilters             1.5.0
parso                     0.8.3
pathspec                  0.11.2
pccm                      0.4.8
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    10.0.0
pip                       23.2.1
pkgutil_resolve_name      1.3.10
platformdirs              3.10.0
plotly                    5.16.1
pluggy                    1.3.0
plyfile                   1.0.1
portalocker               2.7.0
prettytable               3.9.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
protobuf                  4.24.3
psutil                    5.9.5
ptyprocess                0.7.0
pure-eval                 0.2.2
pyasn1                    0.5.0
pyasn1-modules            0.3.0
pybind11                  2.11.1
pycocotools               2.0.7
pycodestyle               2.11.0
pycparser                 2.21
pyflakes                  3.1.0
Pygments                  2.16.1
pyparsing                 3.1.1
pyquaternion              0.9.9
pytest                    7.4.2
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.3.post1
PyWavelets                1.4.1
PyYAML                    6.0.1
pyzmq                     25.1.1
qtconsole                 5.4.4
QtPy                      2.4.0
referencing               0.30.2
requests                  2.31.0
requests-oauthlib         1.3.1
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.2
rsa                       4.9
scikit-image              0.19.3
scikit-learn              1.3.0
scipy                     1.10.1
Send2Trash                1.8.2
setuptools                68.0.0
Shapely                   1.8.5
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
spconv-cu114              2.3.6
stack-data                0.6.2
sympy                     1.12
tenacity                  8.2.3
tensorboard               2.14.0
tensorboard-data-server   0.7.1
termcolor                 2.3.0
terminado                 0.17.1
terminaltables            3.1.10
threadpoolctl             3.2.0
tifffile                  2023.7.10
tinycss2                  1.2.1
tomli                     2.0.1
torch                     2.0.1
torchvision               0.15.2
tornado                   6.3.3
tqdm                      4.66.1
traitlets                 5.9.0
trimesh                   2.35.39
triton                    2.0.0
typing_extensions         4.7.1
tzdata                    2023.3
uri-template              1.3.0
urllib3                   1.26.16
wcwidth                   0.2.6
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.3
Werkzeug                  2.3.7
wheel                     0.38.4
widgetsnbextension        4.0.8
yapf                      0.40.1
zipp                      3.16.2

**Comment by LaCandela** [comment]
I've found the solution, one needs too install all the software versions exactly as they are in the installation doc.
