### ISSUE TITLE
numba:SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by bccw2021** [NVlabs/FB-BEV#35]
Traceback (most recent call last):
  File "./tools/test.py", line 15, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/home/jl/FB-BEV/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/home/jl/FB-BEV/mmdet3d/apis/inference.py", line 12, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes, Coord3DMode,
  File "/home/jl/FB-BEV/mmdet3d/core/__init__.py", line 4, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/jl/FB-BEV/mmdet3d/core/evaluation/__init__.py", line 4, in <module>
    from .kitti_utils import kitti_eval, kitti_eval_coco_style
  File "/home/jl/FB-BEV/mmdet3d/core/evaluation/kitti_utils/__init__.py", line 2, in <module>
    from .eval import kitti_eval, kitti_eval_coco_style
  File "/home/jl/FB-BEV/mmdet3d/core/evaluation/kitti_utils/eval.py", line 5, in <module>
    import numba
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 34725) of binary: /home/jl/anaconda3/envs/open-mmlab/bin/python
Traceback (most recent call last):
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jl/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------

**Comment by bccw2021** [comment]
(open-mmlab) jl@jl-OMEN:~/FB-BEV$ pip list | grep "numba\|llvmlite\|numpy"                                                                                            
llvmlite                      0.36.0
numba                         0.53.0
numpy                         1.24.1
(open-mmlab) jl@jl-OMEN:~/FB-BEV$ pip uninstall numpy
Found existing installation: numpy 1.24.1
Uninstalling numpy-1.24.1:
  Would remove:
    /home/jl/.local/bin/f2py
    /home/jl/.local/bin/f2py3
    /home/jl/.local/bin/f2py3.8
    /home/jl/.local/lib/python3.8/site-packages/numpy-1.24.1.dist-info/*
    /home/jl/.local/lib/python3.8/site-packages/numpy.libs/libgfortran-040039e1.so.5.0.0
    /home/jl/.local/lib/python3.8/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so
    /home/jl/.local/lib/python3.8/site-packages/numpy.libs/libquadmath-96973f99.so.0.0.0
    /home/jl/.local/lib/python3.8/site-packages/numpy/*
Proceed (Y/n)? Y
  Successfully uninstalled numpy-1.24.1
(open-mmlab) jl@jl-OMEN:~/FB-BEV$ pip install numpy==1.23.5
